Change project && test CI

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -24,149 +24,149 @@ jobs:
         with:
           access_token: ${{ github.token }}
 
-  mdbook-build:
-    needs: cancel-previous-runs
-    runs-on: ubuntu-latest
-    steps:
-      - uses: actions/checkout@v2
-      - uses: actions-rs/toolchain@v1
-        with:
-          profile: minimal
-          toolchain: stable
-      - uses: Swatinem/rust-cache@v1
-      - name: mdbook build
-        uses: peaceiris/actions-mdbook@v1
-        with:
-          mdbook-version: '0.4.17'
+  # mdbook-build:
+  #   needs: cancel-previous-runs
+  #   runs-on: ubuntu-latest
+  #   steps:
+  #     - uses: actions/checkout@v2
+  #     - uses: actions-rs/toolchain@v1
+  #       with:
+  #         profile: minimal
+  #         toolchain: stable
+  #     - uses: Swatinem/rust-cache@v1
+  #     - name: mdbook build
+  #       uses: peaceiris/actions-mdbook@v1
+  #       with:
+  #         mdbook-version: '0.4.17'
 
-  mdbook-lint:
-    needs: cancel-previous-runs
-    runs-on: ubuntu-latest
-    steps:
-      - uses: actions/checkout@v3
-      - uses: actions/setup-node@v3
-        with:
-          node-version: 18
-      - run: |
-          npm install -g markdownlint-cli@0.31.1
-          markdownlint --config .markdownlintrc **/*.md docs/src/
+  # mdbook-lint:
+  #   needs: cancel-previous-runs
+  #   runs-on: ubuntu-latest
+  #   steps:
+  #     - uses: actions/checkout@v3
+  #     - uses: actions/setup-node@v3
+  #       with:
+  #         node-version: 18
+  #     - run: |
+  #         npm install -g markdownlint-cli@0.31.1
+  #         markdownlint --config .markdownlintrc **/*.md docs/src/
 
-  cargo-unused-deps-check:
-    needs: cancel-previous-runs
-    runs-on: ubuntu-latest
-    steps:
-      - uses: actions/checkout@v2
-      - uses: actions-rs/toolchain@v1
-        with:
-          toolchain: nightly
-          default: true
-      - uses: Swatinem/rust-cache@v1
-      - name: Install cargo-udeps
-        uses: actions-rs/cargo@v1
-        with:
-          command: install
-          args: cargo-udeps
-      - name: Check Unused Deps
-        uses: actions-rs/cargo@v1
-        with:
-          command: udeps
-          args: --locked --all-targets --features postgres
+  # cargo-unused-deps-check:
+  #   needs: cancel-previous-runs
+  #   runs-on: ubuntu-latest
+  #   steps:
+  #     - uses: actions/checkout@v2
+  #     - uses: actions-rs/toolchain@v1
+  #       with:
+  #         toolchain: nightly
+  #         default: true
+  #     - uses: Swatinem/rust-cache@v1
+  #     - name: Install cargo-udeps
+  #       uses: actions-rs/cargo@v1
+  #       with:
+  #         command: install
+  #         args: cargo-udeps
+  #     - name: Check Unused Deps
+  #       uses: actions-rs/cargo@v1
+  #       with:
+  #         command: udeps
+  #         args: --locked --all-targets --features postgres
 
-  cargo-toml-fmt-check:
-    needs: cancel-previous-runs
-    runs-on: ubuntu-latest
-    steps:
-      - uses: actions/checkout@v2
-      - uses: actions-rs/toolchain@v1
-        with:
-          toolchain: stable
-      - uses: Swatinem/rust-cache@v1
-      - name: Install Cargo.toml linter
-        uses: baptiste0928/cargo-install@v1
-        with:
-          crate: cargo-toml-lint
-          version: '0.1'
-      - name: Run Cargo.toml linter
-        run: git ls-files | grep Cargo.toml$ | xargs --verbose -n 1 cargo-toml-lint
+  # cargo-toml-fmt-check:
+  #   needs: cancel-previous-runs
+  #   runs-on: ubuntu-latest
+  #   steps:
+  #     - uses: actions/checkout@v2
+  #     - uses: actions-rs/toolchain@v1
+  #       with:
+  #         toolchain: stable
+  #     - uses: Swatinem/rust-cache@v1
+  #     - name: Install Cargo.toml linter
+  #       uses: baptiste0928/cargo-install@v1
+  #       with:
+  #         crate: cargo-toml-lint
+  #         version: '0.1'
+  #     - name: Run Cargo.toml linter
+  #       run: git ls-files | grep Cargo.toml$ | xargs --verbose -n 1 cargo-toml-lint
 
-  cargo-verifications:
-    runs-on: ubuntu-latest
-    services:
-      postgres:
-        image: postgres:latest
-        env:
-          POSTGRES_PASSWORD: my-secret
-          POSTGRES_DB: postgres
-          POSTGRES_USER: postgres
-        ports:
-          - 5432:5432
-        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
-    needs:
-      - cancel-previous-runs
-      - cargo-unused-deps-check
-      - cargo-toml-fmt-check
-    strategy:
-      matrix:
-        include:
-          - command: fmt
-            args: --all --verbose -- --check
-          - command: clippy
-            args: --all-features --all-targets -- -D warnings -Aclippy::extra-unused-lifetimes
-          - command: check
-            args: --locked --workspace --all-features --all-targets
-            env:
-              RUSTFLAGS: '-D warnings'
-          - command: build
-            args: --locked --workspace --all-features --all-targets
-            env:
-              RUSTFLAGS: '-D warnings'
-          # Default features
-          - command: test
-            args: --locked --workspace
-          # All features
-          - command: test
-            args: --locked --all-targets --all-features --workspace
-            env:
-              RUSTFLAGS: '-D warnings'
-          # No default features
-          - command: test
-            args: --locked --all-targets --no-default-features --workspace
-            env:
-              RUSTFLAGS: '-D warnings'
-    # disallow any job that takes longer than 30 minutes
-    timeout-minutes: 45
-    continue-on-error: ${{ matrix.skip-error || false }}
-    steps:
-      - uses: actions/checkout@v3
-      - uses: actions-rs/toolchain@v1
-        with:
-          toolchain: stable
-      - uses: Swatinem/rust-cache@v1
-        with:
-          key: '${{ matrix.command }} ${{ matrix.args }}'
-      - run: cargo install diesel_cli
-      - run: |
-          cd schema
-          diesel migration run --migration-dir migrations/postgres/
-          cargo fmt
-      - name: ${{ matrix.command }} ${{ matrix.args }}
-        uses: actions-rs/cargo@v1
-        with:
-          command: ${{ matrix.command }}
-          args: ${{ matrix.args }}
-      - name: Notify if Job Fails
-        uses: ravsamhq/notify-slack-action@v1
-        if: always() && github.ref == 'refs/heads/master'
-        with:
-          status: ${{ job.status }}
-          token: ${{ secrets.GITHUB_TOKEN }}
-          notification_title: '{workflow} has {status_message}'
-          message_format: '{emoji} *{workflow}* {status_message} in <{repo_url}|{repo}> : <{run_url}|View Run Results>'
-          footer: ''
-          notify_when: 'failure'
-        env:
-          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_NOTIFY_BUILD }}
-          RUSTFLAGS: -D warnings
+  # cargo-verifications:
+  #   runs-on: ubuntu-latest
+  #   services:
+  #     postgres:
+  #       image: postgres:latest
+  #       env:
+  #         POSTGRES_PASSWORD: my-secret
+  #         POSTGRES_DB: postgres
+  #         POSTGRES_USER: postgres
+  #       ports:
+  #         - 5432:5432
+  #       options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
+  #   needs:
+  #     - cancel-previous-runs
+  #     - cargo-unused-deps-check
+  #     - cargo-toml-fmt-check
+  #   strategy:
+  #     matrix:
+  #       include:
+  #         - command: fmt
+  #           args: --all --verbose -- --check
+  #         - command: clippy
+  #           args: --all-features --all-targets -- -D warnings -Aclippy::extra-unused-lifetimes
+  #         - command: check
+  #           args: --locked --workspace --all-features --all-targets
+  #           env:
+  #             RUSTFLAGS: '-D warnings'
+  #         - command: build
+  #           args: --locked --workspace --all-features --all-targets
+  #           env:
+  #             RUSTFLAGS: '-D warnings'
+  #         # Default features
+  #         - command: test
+  #           args: --locked --workspace
+  #         # All features
+  #         - command: test
+  #           args: --locked --all-targets --all-features --workspace
+  #           env:
+  #             RUSTFLAGS: '-D warnings'
+  #         # No default features
+  #         - command: test
+  #           args: --locked --all-targets --no-default-features --workspace
+  #           env:
+  #             RUSTFLAGS: '-D warnings'
+  #   # disallow any job that takes longer than 30 minutes
+  #   timeout-minutes: 45
+  #   continue-on-error: ${{ matrix.skip-error || false }}
+  #   steps:
+  #     - uses: actions/checkout@v3
+  #     - uses: actions-rs/toolchain@v1
+  #       with:
+  #         toolchain: stable
+  #     - uses: Swatinem/rust-cache@v1
+  #       with:
+  #         key: '${{ matrix.command }} ${{ matrix.args }}'
+  #     - run: cargo install diesel_cli
+  #     - run: |
+  #         cd schema
+  #         diesel migration run --migration-dir migrations/postgres/
+  #         cargo fmt
+  #     - name: ${{ matrix.command }} ${{ matrix.args }}
+  #       uses: actions-rs/cargo@v1
+  #       with:
+  #         command: ${{ matrix.command }}
+  #         args: ${{ matrix.args }}
+  #     - name: Notify if Job Fails
+  #       uses: ravsamhq/notify-slack-action@v1
+  #       if: always() && github.ref == 'refs/heads/master'
+  #       with:
+  #         status: ${{ job.status }}
+  #         token: ${{ secrets.GITHUB_TOKEN }}
+  #         notification_title: '{workflow} has {status_message}'
+  #         message_format: '{emoji} *{workflow}* {status_message} in <{repo_url}|{repo}> : <{run_url}|View Run Results>'
+  #         footer: ''
+  #         notify_when: 'failure'
+  #       env:
+  #         SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_NOTIFY_BUILD }}
+  #         RUSTFLAGS: -D warnings
 
   publish-fuel-indexer-binaries:
     name: Release fuel-indexer binaries
@@ -174,34 +174,33 @@ jobs:
     # Only do this job if publishing a release
     needs:
       - cancel-previous-runs
-      - cargo-unused-deps-check
-      - cargo-toml-fmt-check
-    if: github.event_name == 'release' && github.event.action == 'published'
+      # - cargo-verifications
+    # if: github.event_name == 'release' && github.event.action == 'published'
     strategy:
       matrix:
         job:
-          - os: ubuntu-latest
-            platform: linux
-            target: x86_64-unknown-linux-gnu
-            cross_image: x86_64-linux-gnu
+          # - os: ubuntu-latest
+          #   platform: linux
+          #   target: x86_64-unknown-linux-gnu
+          #   cross_image: x86_64-linux-gnu
           - os: ubuntu-latest
             platform: linux
             target: x86_64-unknown-linux-musl
             cross_image: x86_64-linux-musl
-          - os: ubuntu-latest
-            platform: linux-arm
-            target: aarch64-unknown-linux-gnu
-            cross_image: aarch64-linux-gnu
-          - os: ubuntu-latest
-            platform: linux-arm
-            target: aarch64-unknown-linux-musl
-            cross_image: aarch64-linux-musl
-          - os: macos-latest
-            platform: darwin
-            target: x86_64-apple-darwin
-          - os: macos-latest
-            platform: darwin-arm
-            target: aarch64-apple-darwin
+          # - os: ubuntu-latest
+          #   platform: linux-arm
+          #   target: aarch64-unknown-linux-gnu
+          #   cross_image: aarch64-linux-gnu
+          # - os: ubuntu-latest
+          #   platform: linux-arm
+          #   target: aarch64-unknown-linux-musl
+          #   cross_image: aarch64-linux-musl
+          # - os: macos-latest
+          #   platform: darwin
+          #   target: x86_64-apple-darwin
+          # - os: macos-latest
+          #   platform: darwin-arm
+          #   target: aarch64-apple-darwin
     steps:
       - name: Checkout repository
         uses: actions/checkout@v3
@@ -245,7 +244,7 @@ jobs:
 
       - name: Build fuel-executor
         run: |
-          cross build --profile=release --target ${{ matrix.job.target }} -p fuel-executor
+          cross build --locked --profile=release --target ${{ matrix.job.target }} -p fuel-executor
       - name: Strip release binary linux x86_64
         if: matrix.job.platform == 'linux'
         run: strip "target/${{ matrix.job.target }}/release/fuel-executor"
@@ -312,75 +311,76 @@ jobs:
         env:
           SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_NOTIFY_BUILD }}
 
-  publish-docker-image:
-    needs: cargo-toml-fmt-check
+  # publish-docker-image:
+  #   needs: cargo-toml-fmt-check
 
-    if: always()
-    runs-on: ubuntu-latest
-    permissions:
-      contents: read
-      packages: write
-    steps:
-      # This is a way to make this job run after publish-crates even if it's skipped on master or pr branches
-      # https://stackoverflow.com/a/69252812/680811
-      - name: fail if any dependent jobs failed
-        if: ${{ contains(needs.*.result, 'failure') }}
-        run: exit 1
+  #   if: always()
+  #   runs-on: ubuntu-latest
+  #   permissions:
+  #     contents: read
+  #     packages: write
+  #   steps:
+  #     # This is a way to make this job run after publish-crates even if it's skipped on master or pr branches
+  #     # https://stackoverflow.com/a/69252812/680811
+  #     - name: fail if any dependent jobs failed
+  #       if: ${{ contains(needs.*.result, 'failure') }}
+  #       run: exit 1
 
-      - name: Checkout repository
-        uses: actions/checkout@v3
+  #     - name: Checkout repository
+  #       uses: actions/checkout@v3
 
-      - name: Docker meta
-        id: meta
-        uses: docker/metadata-action@v3
-        with:
-          images: |
-            ghcr.io/fuellabs/fuel-indexer
-          tags: |
-            type=sha
-            type=ref,event=branch
-            type=ref,event=tag
-            type=semver,pattern={{raw}}
-          flavor: |
-            latest=${{ github.ref == 'refs/heads/master' }}
-      - name: Set up Docker Buildx
-        uses: docker/setup-buildx-action@v1
+  #     - name: Docker meta
+  #       id: meta
+  #       uses: docker/metadata-action@v3
+  #       with:
+  #         images: |
+  #           ghcr.io/fuellabs/fuel-indexer
+  #         tags: |
+  #           type=sha
+  #           type=ref,event=branch
+  #           type=ref,event=tag
+  #           type=semver,pattern={{raw}}
+  #         flavor: |
+  #           latest=${{ github.ref == 'refs/heads/master' }}
+  #     - name: Set up Docker Buildx
+  #       uses: docker/setup-buildx-action@v1
 
-      - name: Log in to the ghcr.io registry
-        uses: docker/login-action@v1
-        with:
-          registry: ${{ env.REGISTRY }}
-          username: ${{ github.repository_owner }}
-          password: ${{ secrets.GITHUB_TOKEN }}
+  #     - name: Log in to the ghcr.io registry
+  #       uses: docker/login-action@v1
+  #       with:
+  #         registry: ${{ env.REGISTRY }}
+  #         username: ${{ github.repository_owner }}
+  #         password: ${{ secrets.GITHUB_TOKEN }}
 
-      - name: Build and push the image to ghcr.io
-        uses: docker/build-push-action@v2
-        with:
-          context: .
-          file: deployment/Dockerfile
-          push: true
-          tags: ${{ steps.meta.outputs.tags }}
-          labels: ${{ steps.meta.outputs.labels }}
-          cache-from: type=gha
-          cache-to: type=gha,mode=max
+  #     - name: Build and push the image to ghcr.io
+  #       uses: docker/build-push-action@v2
+  #       with:
+  #         context: .
+  #         file: deployment/Dockerfile
+  #         push: true
+  #         tags: ${{ steps.meta.outputs.tags }}
+  #         labels: ${{ steps.meta.outputs.labels }}
+  #         cache-from: type=gha
+  #         cache-to: type=gha,mode=max
 
-      - name: Notify if Job Fails
-        uses: ravsamhq/notify-slack-action@v1
-        if: always() && (github.ref == 'refs/heads/master' || github.ref_type == 'tag')
-        with:
-          status: ${{ job.status }}
-          token: ${{ secrets.GITHUB_TOKEN }}
-          notification_title: '{workflow} has {status_message}'
-          message_format: '{emoji} *{workflow}* {status_message} in <{repo_url}|{repo}> : <{run_url}|View Run Results>'
-          footer: ''
-          notify_when: 'failure'
-        env:
-          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_NOTIFY_BUILD }}
+  #     - name: Notify if Job Fails
+  #       uses: ravsamhq/notify-slack-action@v1
+  #       if: always() && (github.ref == 'refs/heads/master' || github.ref_type == 'tag')
+  #       with:
+  #         status: ${{ job.status }}
+  #         token: ${{ secrets.GITHUB_TOKEN }}
+  #         notification_title: '{workflow} has {status_message}'
+  #         message_format: '{emoji} *{workflow}* {status_message} in <{repo_url}|{repo}> : <{run_url}|View Run Results>'
+  #         footer: ''
+  #         notify_when: 'failure'
+  #       env:
+  #         SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_NOTIFY_BUILD }}
 
   validation-complete:
     needs:
-      - cargo-verifications
-      - mdbook-build
+      - publish-fuel-indexer-binaries
+      # - cargo-verifications
+      # - mdbook-build
     runs-on: ubuntu-latest
     steps:
       - run: true
